### ISSUE TITLE
ONBUILD use case

### ISSUE THREAD

**Issue by netserf** [inhumantsar/docker-ansible#12]
Just a question. So I'm assuming the typical use case for ONBUILD is for playbook runs against real systems whereas runs against a Docker container is mostly about testing. 

Is this an accurate assumption?

**Comment by inhumantsar** [comment]
ONBUILD only differs in that you're packaging the playbook and dependencies. Both the regular and the ONBUILD images are perfectly capable of running plays against live hosts. 

Depending on the setup and goals, the regular image would be just fine for running against live hosts. Jenkins or w/e could cache the regular image and use it to run any playbook. It would source the PyPI, system and Ansible Galaxy deps on-the-fly then run the playbook against the host inventory provided. 

If your systems are air-gapped, version sensitive, usage sensitive, or restrict outgoing SSH, then sourcing deps on-the-fly gets tricky. That's when it starts to make sense to package everything into a shippable bundle and stamp a version on it.

**Comment by netserf** [comment]
Okay, that makes sense. Thanks!
